package com.techelevator.model;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

public class Pothole {

    int reportId;   //generated by DB
    int potholeId;  //generated by DB
    int reportingUser; //ID of user who reported

    boolean verified;   //true/false
    String repairStatus; //not-repaired, inspected, scheduled for repair, repaired
    String severity; //tbd

    @Valid
    Address address;

    public Pothole() {
    }

    public Pothole(int reportingUser, Address address) {
        this.reportingUser = reportingUser;
        this.address = address;
        this.repairStatus = "not repaired";
    }

    public Pothole(int reportId, int potholeId, int reportingUser, boolean verified, String repairStatus, String severity, Address address) {
        this.reportId = reportId;
        this.potholeId = potholeId;
        this.reportingUser = reportingUser;
        this.verified = verified;
        this.repairStatus = repairStatus;
        this.severity = severity;
        this.address = address;
    }

    public int getReportId() {
        return reportId;
    }

    public void setReportId(int reportId) {
        this.reportId = reportId;
    }

    public int getPotholeId() {
        return potholeId;
    }

    public void setPotholeId(int potholeId) {
        this.potholeId = potholeId;
    }

    public int getReportingUser() {
        return reportingUser;
    }

    public void setReportingUser(int reportingUser) {
        this.reportingUser = reportingUser;
    }

    public boolean isVerified() {
        return verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    public String getRepairStatus() {
        return repairStatus;
    }

    public void setRepairStatus(String repairStatus) {
        this.repairStatus = repairStatus;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Pothole{" +
                "reportId=" + reportId +
                ", potholeId=" + potholeId +
                ", reportingUser=" + reportingUser +
                ", verified=" + verified +
                ", repairStatus='" + repairStatus + '\'' +
                ", severity='" + severity + '\'' +
                ", address=" + address +
                '}';
    }
}
