package com.techelevator.model;

import javax.validation.Valid;
import javax.validation.constraints.Positive;

public class Report {

    private Long reportId;   //generated by DB
    @Positive
    private Long reportingUser; //ID of user who reported

    private Pothole pothole = null;
    private Drain drain = null;


    public Report() {
    }

    public Report(Long reportingUser, Pothole pothole) {
        this.reportingUser = reportingUser;
        this.pothole = pothole;
    }

    public Report(Long reportingUser, Drain drain) {
        this.reportingUser = reportingUser;
        this.drain = drain;
    }

    public Report(Pothole pothole) {
        this.reportId = 0L;
        this.reportingUser = 0L;
        this.pothole = pothole;

    }

    public Report(Drain drain) {
        this.reportId = 0L;
        this.reportingUser = 0L;
        this.drain = drain;
    }

    public Report(Long reportId, Long reportingUser, Pothole pothole) {
        this.reportId = reportId;
        this.reportingUser = reportingUser;
        this.pothole = pothole;
    }

    public Report(Long reportId, Long reportingUser, Drain drain) {
        this.reportId = reportId;
        this.reportingUser = reportingUser;
        this.drain = drain;
    }

    public Long getReportId() {
        return reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public Long getReportingUser() {
        return reportingUser;
    }

    public void setReportingUser(Long reportingUser) {
        this.reportingUser = reportingUser;
    }

    public Pothole getPothole() {
        return pothole;
    }

    public void setPothole(Pothole pothole) {
        this.pothole = pothole;
    }

    public Drain getDrain() {
        return drain;
    }

    public void setDrain(Drain drain) {
        this.drain = drain;
    }


    @Override
    public String toString() {
        return "Report{" +
                "reportId=" + reportId +
                ", reportingUser=" + reportingUser +
                ", pothole=" + pothole +
                ", drain=" + drain +
                '}';
    }
}
