package com.techelevator.model;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

public class Report {

    Long reportId;   //generated by DB
    @Positive
    Long reportingUser; //ID of user who reported

    @Valid
    Pothole pothole;
    //Report can later include a storm drain, etc.

    public Report() {
    }

    public Report(Pothole pothole) {
        this.reportId = 0L;
        this.reportingUser = 0L;
        this.pothole = pothole;
    }

    public Report(Long reportId, Long reportingUser, Pothole pothole) {
        this.reportId = reportId;
        this.reportingUser = reportingUser;
        this.pothole = pothole;
    }

    public Long getReportId() {
        return reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public Long getReportingUser() {
        return reportingUser;
    }

    public void setReportingUser(Long reportingUser) {
        this.reportingUser = reportingUser;
    }

    public Pothole getPothole() {
        return pothole;
    }

    public void setPothole(Pothole pothole) {
        this.pothole = pothole;
    }

    @Override
    public String toString() {
        return "Report{" +
                "reportId=" + reportId +
                ", reportingUser=" + reportingUser +
                ", pothole=" + pothole +
                '}';
    }
}
